// examples/sveltekit/src/routes/http-demo/+page.svelte
<script lang="ts">
import type { userModel } from '@examples/shared'
import type z from 'zod'
import { apiClient } from '$lib/api-client'

type User = z.infer<typeof userModel>

let users: User[] = $state([])
let name = $state('')
let email = $state('')
let loading = $state(false)
let selectedUserId = $state('')

async function handleGetUsers() {
  loading = true
  try {
    const response = await apiClient.api.users.get({
      query: { page: 1, limit: 10 },
    })
    if (response.data) {
      users = response.data
    }
  } catch (error) {
    console.error('Error fetching users:', error)
  } finally {
    loading = false
  }
}

async function handleCreateUser() {
  if (!name || !email) return
  loading = true
  try {
    const response = await apiClient.api.users.post({
      json: { name, email },
    })
    if (response.data) {
      users = [...users, response.data]
      name = ''
      email = ''
    }
  } catch (error) {
    console.error('Error creating user:', error)
  } finally {
    loading = false
  }
}

async function handleUpdateUser() {
  if (!selectedUserId || !name || !email) return
  loading = true
  try {
    const response = await apiClient.api.users.id(selectedUserId).put({
      json: { name, email },
    })

    if (response.data) {
      users = users.map((u) => (u.id === selectedUserId ? response.data : u))
      name = ''
      email = ''
      selectedUserId = ''
    }
  } catch (error) {
    console.error('Error updating user:', error)
  } finally {
    loading = false
  }
}

async function handlePatchUser() {
  if (!selectedUserId) return
  loading = true
  try {
    const response = await apiClient.api.users.id(selectedUserId).patch({
      json: { name: name || undefined, email: email || undefined },
    })
    if (response.data) {
      users = users.map((u) => (u.id === selectedUserId ? response.data : u))
      name = ''
      email = ''
      selectedUserId = ''
    }
  } catch (error) {
    console.error('Error patching user:', error)
  } finally {
    loading = false
  }
}

async function handleDeleteUser(userId: string) {
  loading = true
  try {
    await apiClient.api.users.id(userId).delete()
    users = users.filter((u) => u.id !== userId)
  } catch (error) {
    console.error('Error deleting user:', error)
  } finally {
    loading = false
  }
}

function selectUser(user: User) {
  selectedUserId = user.id
  name = user.name
  email = user.email
}

function handleSubmit(e: Event) {
  e.preventDefault()
}
</script>

<article>
  <header>
    <h2>User Management</h2>
    <p>Demonstrating all HTTP methods</p>
  </header>

  <form onsubmit={handleSubmit}>
    <fieldset>
      <legend>Create or Edit User</legend>
      <div>
        <label for="name">Name</label>
        <input
          id="name"
          placeholder="Enter name"
          bind:value={name}
          type="text"
        />
      </div>

      <div>
        <label for="email">Email</label>
        <input
          id="email"
          placeholder="Enter email"
          bind:value={email}
          type="email"
        />
      </div>

      <div class="flex-row">
        <button
          type="button"
          onclick={handleCreateUser}
          disabled={loading}
          class="btn-success"
        >
          POST - Create
        </button>
        <button
          type="button"
          onclick={handleUpdateUser}
          disabled={loading || !selectedUserId}
          class="btn-primary"
        >
          PUT - Update
        </button>
        <button
          type="button"
          onclick={handlePatchUser}
          disabled={loading || !selectedUserId}
          class="btn-secondary"
        >
          PATCH - Partial
        </button>
      </div>
    </fieldset>
  </form>

  <button
    type="button"
    onclick={handleGetUsers}
    disabled={loading}
    class="btn-primary"
  >
    GET - Fetch All Users
  </button>

  {#if users.length > 0}
    <div class="list-container">
      <strong>Users ({users.length})</strong>
      {#each users as user (user.id)}
        <div
          class="list-item {selectedUserId === user.id ? 'selected' : ''}"
          onclick={() => selectUser(user)}
        >
          <div
            style="display: flex; justify-content: space-between; align-items: center;"
          >
            <div>
              <strong>{user.name}</strong>
              <small>{user.email}</small>
            </div>
            <button
              type="button"
              onclick={(e) => {
                e.stopPropagation()
                handleDeleteUser(user.id)
              }}
              disabled={loading}
              class="btn-danger"
            >
              DELETE
            </button>
          </div>
        </div>
      {/each}
    </div>
  {/if}
</article>

// examples/react/src/routes/http-demo.tsx
import { createFileRoute } from '@tanstack/react-router'
import { useState } from 'react'
import { apiClient } from '@/api/api-client'

interface User {
  id: string
  name: string
  email: string
  createdAt: string
}

export const Route = createFileRoute('/http-demo')({
  component: RouteComponent,
})

function RouteComponent() {
  const [users, setUsers] = useState<User[]>([])
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [loading, setLoading] = useState(false)
  const [selectedUserId, setSelectedUserId] = useState('')

  const handleGetUsers = async () => {
    setLoading(true)
    try {
      const response = await apiClient.users.get({
        query: { page: 1, limit: 10 },
      })
      if (response.data) {
        setUsers(response.data)
      }
    } catch (error) {
      console.error('Error fetching users:', error)
    } finally {
      setLoading(false)
    }
  }

  const handleCreateUser = async () => {
    if (!name || !email) return
    setLoading(true)
    try {
      const response = await apiClient.users.post({
        json: { name, email },
      })
      if (response.data) {
        setUsers([...users, response.data])
        setName('')
        setEmail('')
      }
    } catch (error) {
      console.error('Error creating user:', error)
    } finally {
      setLoading(false)
    }
  }

  const handleUpdateUser = async () => {
    if (!selectedUserId || !name || !email) return
    setLoading(true)
    try {
      const response = await apiClient.users.id(selectedUserId).put({
        json: { name, email },
      })

      if (response.data) {
        setUsers(
          users.map((u) => (u.id === selectedUserId ? response.data : u)),
        )
        setName('')
        setEmail('')
        setSelectedUserId('')
      }
    } catch (error) {
      console.error('Error updating user:', error)
    } finally {
      setLoading(false)
    }
  }

  const handlePatchUser = async () => {
    if (!selectedUserId) return
    setLoading(true)
    try {
      const response = await apiClient.users.id(selectedUserId).patch({
        param: { id: selectedUserId },
        json: { name: name || undefined, email: email || undefined },
      })
      if (response.data) {
        setUsers(
          users.map((u) => (u.id === selectedUserId ? response.data : u)),
        )
        setName('')
        setEmail('')
        setSelectedUserId('')
      }
    } catch (error) {
      console.error('Error patching user:', error)
    } finally {
      setLoading(false)
    }
  }

  const handleDeleteUser = async (userId: string) => {
    setLoading(true)
    try {
      await apiClient.users.id(userId).delete()
      setUsers(users.filter((u) => u.id !== userId))
    } catch (error) {
      console.error('Error deleting user:', error)
    } finally {
      setLoading(false)
    }
  }

  return (
    <article>
      <header>
        <h2>User Management</h2>
        <p>Demonstrating all HTTP methods</p>
      </header>

      <form onSubmit={(e) => e.preventDefault()}>
        <fieldset>
          <legend>Create or Edit User</legend>
          <div>
            <label htmlFor="name">Name</label>
            <input
              id="name"
              placeholder="Enter name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              type="text"
            />
          </div>

          <div>
            <label htmlFor="email">Email</label>
            <input
              id="email"
              placeholder="Enter email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              type="email"
            />
          </div>

          <div className="flex-row">
            <button
              type="button"
              onClick={handleCreateUser}
              disabled={loading}
              className="btn-success"
            >
              POST - Create
            </button>
            <button
              type="button"
              onClick={handleUpdateUser}
              disabled={loading || !selectedUserId}
              className="btn-primary"
            >
              PUT - Update
            </button>
            <button
              type="button"
              onClick={handlePatchUser}
              disabled={loading || !selectedUserId}
              className="btn-secondary"
            >
              PATCH - Partial
            </button>
          </div>
        </fieldset>
      </form>

      <button
        type="button"
        onClick={handleGetUsers}
        disabled={loading}
        className="btn-primary"
      >
        GET - Fetch All Users
      </button>

      {users.length > 0 && (
        <div className="list-container">
          <strong>Users ({users.length})</strong>
          {users.map((user) => (
            <div
              key={user.id}
              className={`list-item ${selectedUserId === user.id ? 'selected' : ''}`}
              onClick={() => {
                setSelectedUserId(user.id)
                setName(user.name)
                setEmail(user.email)
              }}
            >
              <div
                style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                }}
              >
                <div>
                  <strong>{user.name}</strong>
                  <small>{user.email}</small>
                </div>
                <button
                  type="button"
                  onClick={(e) => {
                    e.stopPropagation()
                    handleDeleteUser(user.id)
                  }}
                  disabled={loading}
                  className="btn-danger"
                >
                  DELETE
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </article>
  )
}
